# Generated by Django 5.2.12 on 2026-03-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionrecord',
            options={'ordering': ['-produce_dt', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='mac1',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='mac2',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='mac3',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='mac4',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='mac5',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='mac6',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='bt_mac',
            field=models.CharField(blank=True, max_length=17, verbose_name='BT_Mac'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='carton_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='cartonNumber'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='chip_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='chip_id'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='pallet_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='palletNumber'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='pcb_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='pcb_label'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='PO_Number'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='produce_dt',
            field=models.DateField(blank=True, null=True, verbose_name='produce_dt'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='serial_number'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='stb_mac',
            field=models.CharField(blank=True, max_length=17, verbose_name='STB_Mac'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='wifi_ap_2g',
            field=models.CharField(blank=True, max_length=17, verbose_name='Wifi_AP_2G'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='wifi_ap_5g',
            field=models.CharField(blank=True, max_length=17, verbose_name='Wifi_AP_5G'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='wifi_client_2g',
            field=models.CharField(blank=True, max_length=17, verbose_name='Wifi_Client_2G'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='wifi_client_5g',
            field=models.CharField(blank=True, max_length=17, verbose_name='Wifi_Client_5G'),
        ),
    ]
